export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8   
export LANGUAGE=en_US.UTF-8
#export TERM=screen-256color
export TERM=xterm-256color
export DISPLAY=:0.0
#eval `dircolors ~/dotfiles/dircolors/dircolors.256dark`
eval `dircolors ~/dotfiles/dircolors/dircolors.ansi-dark`

